### PR TITLE
INSTALL: Move the instructions for RHEL 7 to the wiki

### PR DESCRIPTION
**Pull request by jefft0**
This pull request removes the file with install instructions for RHEL 7 because they have been moved to the wiki https://github.com/operantnetworks/ndn-ind/wiki/Install-NDN-dependencies-on-RHEL-7 .

### CODE REVIEW

**Review by maysax — APPROVED** [review]
Approved

**Comment by jefft0** [comment]
Randy, can you take a look?

**Comment by OperantSWDev** [comment]
Looks fine, but I don't have a reviewer role to approve

**Review by OperantSWDev — APPROVED** [review]
Approved as per scrum of 9/21

**Pull request merged**
